//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class helptexttag
    {
        public int helptexttag_ID { get; set; }
        public int helptext_ID { get; set; }
        public Nullable<int> metatag_ID { get; set; }
    
        public virtual helptext helptext { get; set; }
        public virtual metatag metatag { get; set; }
    }
}
