//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Norges_EnergiEntities : DbContext
    {
        public Norges_EnergiEntities()
            : base("name=Norges_EnergiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<helptext> helptext { get; set; }
        public virtual DbSet<helptexttag> helptexttag { get; set; }
        public virtual DbSet<info> info { get; set; }
        public virtual DbSet<metatag> metatag { get; set; }
        public virtual DbSet<stage1> stage1 { get; set; }
        public virtual DbSet<stage2> stage2 { get; set; }
        public virtual DbSet<stage3> stage3 { get; set; }
        public virtual DbSet<stage4> stage4 { get; set; }
    }
}
