//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string loginname { get; set; }
        public string loginpassword { get; set; }
        public Nullable<int> stage1_ID { get; set; }
    
        public virtual stage1 stage1 { get; set; }
    }
}
